### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by GoodWillGustin** [uxigene/MMM-QRCode#4]
I ran the install command in the modules directory, but am getting:

pi@SmartMirror:~/MagicMirror/modules $ git clone git@github.com:MarinescuEvghenii/MMM-QRCode.git
Cloning into 'MMM-QRCode'...
^[[BPermission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by uxigene** [comment]
It works for me. Try to add your ssh public key into your github account.
